version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmootezmysql"] #Utilisation effective de la variable
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: mootezmysql
      MYSQL_DATABASE: employee_management
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ../backend/backendDevops
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employee_management?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mootezmysql

  frontend:
    build:
      context: ../frontend/frontendDevops
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data: