version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mootezmysql
      MYSQL_DATABASE: employee_management
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ../backend/backendDevops
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employee_management?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mootezmysql

  frontend:
    build:
      context: ../frontend/frontenddevops
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data: